### ISSUE TITLE
Socket connection fails on arm64e iOS 16+

### ISSUE THREAD

**Issue by elihwyma** [Aemulo/Release#2]
Cases where I have confirmed it working: 
- iOS 14 A11
- iOS 14 A9
- iOS 15 A13
- iOS 14 A13
- iOS 16 A11

**Comment by lileeleolee** [comment]
ios16.4.1  A15   blank screen   not working

**Comment by elihwyma** [comment]
Fixed in https://github.com/Aemulo/Release/releases/tag/2.0-589
