### ISSUE TITLE
Failed to connect to nfcd errors.

### ISSUE THREAD

**Issue by gitk01n** [Aemulo/Release#6]
Iphone 11 , ios16.6.1,semi-jailbreak and installed aemulo (Trial), opening the app prompt “Failed to connect to nfcd ... "errors.

**Comment by jhorvitz124** [comment]
Same thing for me. iPhone 13 Pro Max iOS 16.1 running serotonin semi-jailbreak. Says to check tweak injection for NFCD.

**Comment by TheGithubJoshua** [comment]
@gitk01n @jhorvitz124 Serotonin does not support daemon injection so you cannot use Aemulo on devices with Serotonin, however the new version of Aemulo (the one on this repo) does work with Serotonin because I believe this one uses a rebuilt nfcd instead of injecting tweaks into the stock nfcd.

**Comment by elihwyma** [comment]
This repo is exclusively for Aemulo 2.0 issues. Closing as not relevant.
