### ISSUE TITLE
Tweak injection issues

### ISSUE THREAD

**Issue by jhorvitz124** [Aemulo/Release#8]
![image](https://github.com/Aemulo/Release/assets/113337655/1b33fe19-dd52-432f-8bc8-63ec4a2f58e8)

iPhone 13 Pro Max iOS 16.1

**Comment by ryanjg5689** [comment]
I’m still having this issue. Is there a solution to this or is there a different reason this was closed

**Comment by jhorvitz124** [comment]
@ryanjg5689 you need the rootless jailbreak I fixed it by installing the ipa through TrollStore for the free version. Then I bought the paid version because I liked and that didn't appear and I didn't need an ipa file.

**Comment by Ljzd-PRO** [comment]
Install Dopamine and jailbreak, then install Aemulo in Sileo or Zebra
